apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 7.5.4
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      annotations:
        checksum/grafana-datasources: bff02b6fd55e414ce7cf08a5ea2a85e3
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 7.5.4
    spec:
      containers:
      - env:
        - name: GF_RENDERING_SERVER_URL
          value: http://image-render:8081/render
        - name: GF_RENDERING_CALLBACK_URL
          value: http://grafana:3000/
        image: grafana/grafana:7.5.4
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false          
        - mountPath: /grafana-dashboard-definitions/0/wiard
          name: wiard
          readOnly: false             
        - mountPath: /grafana-dashboard-definitions/0/honglilai
          name: honglilai
          readOnly: false        
        - mountPath: /grafana-dashboard-definitions/0/paulustm
          name: paulustm
          readOnly: false   
        - mountPath: /grafana-dashboard-definitions/0/timvandekeer
          name: timvandekeer
          readOnly: false        
        - mountPath: /grafana-dashboard-definitions/0/bramklinkenberg
          name: bramklinkenberg
          readOnly: false                    
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards          
      - configMap:
          name: honglilai
        name: honglilai
      - configMap:
          name: paulustm
        name: paulustm
      - configMap:
          name: timvandekeer
        name: timvandekeer
      - configMap:
          name: bramklinkenberg
        name: bramklinkenberg     
      - configMap:
          name: wiard
        name: wiard            
